import { TrainingItem, TrainingCategory } from './types';

export const trainingCategories: TrainingCategory[] = [
  'Einführungskurs',
  'Kinderkurse',
  'Freies Training',
  'Vereinsausflüge',
];

export const trainings: TrainingItem[] = [
  // Einführungskurs - at least 3 items
  {
    id: 'einfuehrung-2026-01',
    title: 'Einführungskurs Bogenschießen',
    category: 'Einführungskurs',
    startDate: '2026-02-15',
    startTime: '10:00',
    endTime: '12:00',
    locationLabel: 'Aussen',
    spotsTotal: 12,
    spotsInfoText: 'max. 12 Plätze',
    notes: 'Leihbögen werden gestellt. Bitte bequeme Kleidung tragen.',
  },
  {
    id: 'einfuehrung-2026-02',
    title: 'Einführungskurs Bogenschießen',
    category: 'Einführungskurs',
    startDate: '2026-03-08',
    startTime: '14:00',
    endTime: '16:00',
    locationLabel: 'Aussen',
    spotsTotal: 12,
    spotsInfoText: 'max. 12 Plätze',
    notes: 'Leihbögen werden gestellt. Bitte bequeme Kleidung tragen.',
  },
  {
    id: 'einfuehrung-2026-03',
    title: 'Einführungskurs Bogenschießen',
    category: 'Einführungskurs',
    startDate: '2026-04-12',
    startTime: '10:00',
    endTime: '12:00',
    locationLabel: 'Aussen',
    spotsTotal: 12,
    spotsInfoText: 'max. 12 Plätze',
    notes: 'Leihbögen werden gestellt. Bitte bequeme Kleidung tragen.',
  },
  {
    id: 'einfuehrung-2026-04',
    title: 'Einführungskurs Bogenschießen',
    category: 'Einführungskurs',
    startDate: '2026-05-10',
    startTime: '14:00',
    endTime: '16:00',
    locationLabel: 'Aussen',
    spotsTotal: 12,
    spotsInfoText: 'max. 12 Plätze',
  },

  // Kinderkurse - at least 3 items
  {
    id: 'kinderkurs-2026-01',
    title: 'Kinderkurs Bogenschießen (8-12 Jahre)',
    category: 'Kinderkurse',
    startDate: '2026-02-20',
    startTime: '14:00',
    endTime: '15:30',
    locationLabel: 'Aussen',
    spotsTotal: 10,
    spotsInfoText: 'max. 10 Plätze',
    notes: 'Für Kinder von 8-12 Jahren. Leihbögen werden gestellt.',
  },
  {
    id: 'kinderkurs-2026-02',
    title: 'Kinderkurs Bogenschießen (8-12 Jahre)',
    category: 'Kinderkurse',
    startDate: '2026-03-15',
    startTime: '14:00',
    endTime: '15:30',
    locationLabel: 'Aussen',
    spotsTotal: 10,
    spotsInfoText: 'max. 10 Plätze',
    notes: 'Für Kinder von 8-12 Jahren. Leihbögen werden gestellt.',
  },
  {
    id: 'kinderkurs-2026-03',
    title: 'Kinderkurs Bogenschießen (8-12 Jahre)',
    category: 'Kinderkurse',
    startDate: '2026-04-19',
    startTime: '14:00',
    endTime: '15:30',
    locationLabel: 'Aussen',
    spotsTotal: 10,
    spotsInfoText: 'max. 10 Plätze',
    notes: 'Für Kinder von 8-12 Jahren. Leihbögen werden gestellt.',
  },
  {
    id: 'kinderkurs-2026-04',
    title: 'Kinderkurs Bogenschießen (13-16 Jahre)',
    category: 'Kinderkurse',
    startDate: '2026-05-17',
    startTime: '15:00',
    endTime: '17:00',
    locationLabel: 'Aussen',
    spotsTotal: 12,
    spotsInfoText: 'max. 12 Plätze',
    notes: 'Für Jugendliche von 13-16 Jahren.',
  },

  // Freies Training - at least 3 items
  {
    id: 'freies-training-2026-01',
    title: 'Freies Training',
    category: 'Freies Training',
    startDate: '2026-02-05',
    startTime: '18:00',
    endTime: '20:00',
    locationLabel: 'Aussen',
    spotsTotal: 20,
    spotsInfoText: 'max. 20 Plätze',
    notes: 'Offen für alle Mitglieder. Eigene Ausrüstung mitbringen oder ausleihen.',
  },
  {
    id: 'freies-training-2026-02',
    title: 'Freies Training',
    category: 'Freies Training',
    startDate: '2026-02-12',
    startTime: '18:00',
    endTime: '20:00',
    locationLabel: 'Aussen',
    spotsTotal: 20,
    spotsInfoText: 'max. 20 Plätze',
    notes: 'Offen für alle Mitglieder. Eigene Ausrüstung mitbringen oder ausleihen.',
  },
  {
    id: 'freies-training-2026-03',
    title: 'Freies Training',
    category: 'Freies Training',
    startDate: '2026-02-19',
    startTime: '18:00',
    endTime: '20:00',
    locationLabel: 'Aussen',
    spotsTotal: 20,
    spotsInfoText: 'max. 20 Plätze',
    notes: 'Offen für alle Mitglieder. Eigene Ausrüstung mitbringen oder ausleihen.',
  },
  {
    id: 'freies-training-2026-04',
    title: 'Freies Training (Innen)',
    category: 'Freies Training',
    startDate: '2026-02-26',
    startTime: '19:00',
    endTime: '21:00',
    locationLabel: 'Innen',
    spotsTotal: 15,
    spotsInfoText: 'max. 15 Plätze',
    notes: 'Hallen-Training bei schlechtem Wetter. Nur für Mitglieder.',
  },

  // Vereinsausflüge - at least 3 items
  {
    id: 'ausflug-2026-01',
    title: 'Vereinsausflug - 3D Parcours',
    category: 'Vereinsausflüge',
    startDate: '2026-03-22',
    startTime: '09:00',
    endTime: '17:00',
    locationLabel: 'Aussen',
    spotsTotal: 15,
    spotsInfoText: 'max. 15 Plätze',
    notes: 'Ganztägiger Ausflug zu einem 3D-Parcours in der Region. Anmeldung erforderlich.',
  },
  {
    id: 'ausflug-2026-02',
    title: 'Vereinsausflug - Turnierbesuch',
    category: 'Vereinsausflüge',
    startDate: '2026-04-26',
    startTime: '08:00',
    endTime: '18:00',
    locationLabel: 'Aussen',
    spotsTotal: 20,
    spotsInfoText: 'max. 20 Plätze',
    notes: 'Gemeinsamer Besuch eines regionalen Bogensport-Turniers. Anmeldung erforderlich.',
  },
  {
    id: 'ausflug-2026-03',
    title: 'Vereinsausflug - Sommerfest',
    category: 'Vereinsausflüge',
    startDate: '2026-06-14',
    startTime: '11:00',
    endTime: '18:00',
    locationLabel: 'Aussen',
    spotsTotal: 30,
    spotsInfoText: 'max. 30 Plätze',
    notes: 'Jährliches Sommerfest mit Grillen und gemeinsamen Schießen. Familien willkommen.',
  },
  {
    id: 'ausflug-2026-04',
    title: 'Vereinsausflug - Herbstwanderung',
    category: 'Vereinsausflüge',
    startDate: '2026-10-05',
    startTime: '10:00',
    endTime: '16:00',
    locationLabel: 'Aussen',
    spotsTotal: 25,
    spotsInfoText: 'max. 25 Plätze',
    notes: 'Kombinierter Ausflug: Wanderung mit Bogenschießen im Wald. Für alle Altersgruppen.',
  },
];
